version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/marvalero-admin:cached
    
    # Keeps the container running
    command: sleep infinity

    # Network for services to talk to each other
    networks:
      - marvalero-network

networks:
  marvalero-network:
    driver: bridge